version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args: 
        VITE_API_URL: http://localhost:5000
    ports:
      - "5173:3000"
    depends_on:
      - backend
    networks:
      - app-network
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: group7password
      POSTGRES_DB: mydatabase
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build: ./backend
    command: node dist/server.js
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - app-network

  room:
    build: ./room-service
    command: node dist/rooms.js
    ports:
      - "5001:5001"
    env_file:
      - ./room-service/.env
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - app-network

  video:
    build: ./video-service
    command: node dist/videos.js
    ports:
      - "5002:5002"
    env_file:
      - ./video-service/.env
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - app-network

  start-vote:
    build: ./start-vote-service
    command: node dist/start.js
    ports:
      - "5003:5003"
    env_file:
      - ./start-vote-service/.env
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - app-network

  vote:
    build: ./vote-service
    command: node dist/vote.js
    ports:
      - "5004:5004"
    env_file:
      - ./vote-service/.env
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - app-network
  
  end-vote:
    build: ./end-vote-service
    command: node dist/end.js
    ports:
      - "5005:5005"
    env_file:
      - ./end-vote-service/.env
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - app-network
  
  rabbitmq:
    image: rabbitmq:3-management
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: adminpass
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

  video-worker:
    build: ./video-rabbitmq
    command: node dist/rabbitmq.js
    env_file:
      - ./video-rabbitmq/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network

  vote-worker:
    build: ./vote-rabbitmq
    command: node dist/rabbitmq.js
    env_file:
      - ./vote-rabbitmq/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
