StorageClassName: local-path 
Timezone: "Europe/Stockholm"

DBUser: "postgres"
DBPassword: "group7password"
DBImage: postgres:16
DBResourceLimit: false
DBCPU: "1000m"
DBMemory: "1000Mi"
DBStorage: 10Gi
